title: Fake it till you make Git

description: >
  My (opinionated) approach to Git and GitHub

author:
  name: Nicola Erario
  email: 'nicola.erario@gmail.com'

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: 'https://github.com/nicolaerario' }
    - { platform: linkedin, user_url: 'https://www.linkedin.com/in/nicolaerario/' }

plugins:
  - jekyll-remote-theme
