title: Fake it till you make Git

description: >
  An (opinionated) approach to Git and GitHub

author:
  name: Nicola Erario
  email: 'nicola.erario@gmail.com'

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: 'https://github.com/nicolaerario' }
    - { platform: linkedin, user_url: 'https://www.linkedin.com/in/nicolaerario/' }

header_pages:
  - index.md
  - index_it.md

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

paginate: 10
paginate_path: '/page:num/'
